//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.04.27 at 06:11:58 PM CDT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.springboot.com/soapws/loaneligibility", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.springboot.soapws.loaneligibility;
